// FinanceEngineTests.swift
//
// Loads fixtures.json (generated by generate-fixtures.ts via `npx tsx`) and
// asserts that the Swift FinanceEngine produces outputs within 1e-6 of the
// Node.js reference engine for every test case.
//
// IMPORTANT SEMANTICS (verified against TS source):
//   - savingsRate is a PERCENTAGE (0–100+, can be negative), not a 0–1 fraction.
//   - netWorthOutlook returns horizonMonths+1 points: month 0 = current snapshot,
//     months 1..horizon = forecast. A 60-month horizon produces 61 points.
//   - When healthScore.noData == true, estimatedCreditScore == 0 and all sub-scores == 0.
//   - utilization > 1.0 is valid when totalDebt exceeds totalCreditLimit (over-limit).
//
// Run fixture generation first:
//   cd ios/IncomeTrackerTests/Fixtures/gen && npx tsx generate-fixtures.ts
//
// Then run:
//   xcodebuild test -scheme IncomeTrackerTests -destination 'platform=iOS Simulator,name=iPhone 16'

import XCTest
@testable import IncomeTracker

// MARK: - Codable shims for fixture JSON

/// Maps the JSON structure produced by generate-fixtures.ts.
/// The "output" object may have optional keys depending on the test case.
private struct Fixture: Decodable {
    let testName: String
    let input: FixtureInput
    let output: FixtureOutput
}

private struct FixtureInput: Decodable {
    let month: MonthBudget
    let state: LedgerState
    let accounts: [Account]
    let goals: [SavingsGoal]
    let savingsTarget: Double
    let monthlySurplus: Double?
    let horizonMonths: Int?
    let previousMonth: MonthBudget?
}

private struct FixtureOutput: Decodable {
    let projection: Projection
    let debtSummary: DebtSummary
    let assetSummary: AssetSummary
    let netWorthSummary: NetWorthSummary
    let netWorthOutlook: [NetWorthPoint]?
    let monthlyFlow: [MonthlyFlowPoint]?
    let healthScore: HealthScoreBreakdown?
    let signals: [FinancialSignal]?
    let goalSequence: GoalSequenceResult?
    let seededMonth: MonthBudget?
}

// MARK: - Custom Codable for GoalSequenceResult (flatten perGoal dict)

// The JS engine stores `GoalMonthPoint.perGoal` as a plain JSON object keyed by goal ID.
// The Swift type `GoalMonthPoint` uses `[String: GoalMonthPointPerGoal]` which decodes identically.

// MARK: - Test class

final class FinanceEngineTests: XCTestCase {

    // MARK: - Fixture loading (loaded once per test run)

    // Written once in class setUp() before any test runs, read-only afterwards.
    nonisolated(unsafe) private static var fixtures: [Fixture] = []

    override class func setUp() {
        super.setUp()

        // Resolve path: first look inside the test bundle, then fall back to the
        // source-tree location (useful when running under `xcodebuild` from the project root).
        let path = fixturesPath()
        guard let url = path else {
            XCTFail("fixtures.json not found — run `npx tsx generate-fixtures.ts` in ios/IncomeTrackerTests/Fixtures/gen/")
            return
        }

        do {
            let data = try Data(contentsOf: url)
            let decoder = JSONDecoder()
            fixtures = try decoder.decode([Fixture].self, from: data)
        } catch {
            XCTFail("Failed to load fixtures.json: \(error)")
        }
    }

    // MARK: - Helpers

    private static func fixturesPath() -> URL? {
        // 1. Test bundle resource (works when file is in the Xcode target's Copy Bundle Resources phase)
        if let bundleURL = Bundle(for: FinanceEngineTests.self).url(forResource: "fixtures", withExtension: "json") {
            return bundleURL
        }
        // 2. Source-tree relative path (works when running via xcodebuild from repo root)
        let sourceRelative = #file
            .replacingOccurrences(of: "IncomeTrackerTests/Engine/FinanceEngineTests.swift", with: "")
            .appending("IncomeTrackerTests/Fixtures/data/fixtures.json")
        let url = URL(fileURLWithPath: sourceRelative)
        if FileManager.default.fileExists(atPath: url.path) {
            return url
        }
        return nil
    }

    private func fixture(named name: String) throws -> Fixture {
        guard let f = Self.fixtures.first(where: { $0.testName == name }) else {
            throw XCTSkip("Fixture '\(name)' not found in fixtures.json")
        }
        return f
    }

    /// Assert two doubles are equal within 1e-6.
    private func assertEqual(_ actual: Double, _ expected: Double, _ label: String,
                              file: StaticString = #file, line: UInt = #line) {
        XCTAssertEqual(actual, expected, accuracy: 1e-6,
                       "\(label): got \(actual), expected \(expected)", file: file, line: line)
    }

    // MARK: - testProjection

    func testProjection() throws {
        let testCases = ["empty_month", "basic_month", "debt_heavy", "investment_portfolio",
                         "goals_basic", "health_score_good", "health_score_poor", "seed_from_previous"]

        for name in testCases {
            let fix = try fixture(named: name)
            let actual = FinanceEngine.projection(for: fix.input.month)
            let exp    = fix.output.projection

            assertEqual(actual.monthlyIncome,            exp.monthlyIncome,            "\(name).monthlyIncome")
            assertEqual(actual.monthlyExpenses,          exp.monthlyExpenses,          "\(name).monthlyExpenses")
            assertEqual(actual.monthlySurplus,           exp.monthlySurplus,           "\(name).monthlySurplus")
            assertEqual(actual.recurringMonthlyIncome,   exp.recurringMonthlyIncome,   "\(name).recurringMonthlyIncome")
            assertEqual(actual.recurringMonthlyExpenses, exp.recurringMonthlyExpenses, "\(name).recurringMonthlyExpenses")
            assertEqual(actual.recurringMonthlySurplus,  exp.recurringMonthlySurplus,  "\(name).recurringMonthlySurplus")
            assertEqual(actual.annualIncome,             exp.annualIncome,             "\(name).annualIncome")
            assertEqual(actual.annualExpenses,           exp.annualExpenses,           "\(name).annualExpenses")
            assertEqual(actual.annualSurplus,            exp.annualSurplus,            "\(name).annualSurplus")
            assertEqual(actual.savingsRate,              exp.savingsRate,              "\(name).savingsRate")
            assertEqual(actual.paidTotal,                exp.paidTotal,                "\(name).paidTotal")
            assertEqual(actual.unpaidTotal,              exp.unpaidTotal,              "\(name).unpaidTotal")
            XCTAssertEqual(actual.oneOffCount, exp.oneOffCount, "\(name).oneOffCount")
        }
    }

    // MARK: - testDebtSummary

    func testDebtSummary() throws {
        let testCases = ["empty_month", "debt_heavy", "health_score_poor", "net_worth_outlook_60"]

        for name in testCases {
            let fix = try fixture(named: name)
            let actual = FinanceEngine.debtSummary(fix.input.accounts)
            let exp    = fix.output.debtSummary

            assertEqual(actual.totalDebt,        exp.totalDebt,        "\(name).totalDebt")
            assertEqual(actual.totalCreditLimit,  exp.totalCreditLimit, "\(name).totalCreditLimit")
            assertEqual(actual.availableCredit,  exp.availableCredit,  "\(name).availableCredit")
            assertEqual(actual.utilization,      exp.utilization,      "\(name).utilization")
            assertEqual(actual.monthlyMinimums,  exp.monthlyMinimums,  "\(name).monthlyMinimums")
            assertEqual(actual.weightedApr,      exp.weightedApr,      "\(name).weightedApr")
            XCTAssertEqual(actual.nextDueDay,    exp.nextDueDay,       "\(name).nextDueDay")
        }
    }

    // MARK: - testAssetSummary

    func testAssetSummary() throws {
        let testCases = ["empty_month", "investment_portfolio", "health_score_good", "net_worth_outlook_60"]

        for name in testCases {
            let fix = try fixture(named: name)
            let actual = FinanceEngine.assetSummary(fix.input.accounts)
            let exp    = fix.output.assetSummary

            assertEqual(actual.totalAssets,          exp.totalAssets,          "\(name).totalAssets")
            assertEqual(actual.totalCash,            exp.totalCash,            "\(name).totalCash")
            assertEqual(actual.totalSavings,         exp.totalSavings,         "\(name).totalSavings")
            assertEqual(actual.totalInvestments,     exp.totalInvestments,     "\(name).totalInvestments")
            assertEqual(actual.monthlyContributions, exp.monthlyContributions, "\(name).monthlyContributions")
            assertEqual(actual.weightedAssetRate,    exp.weightedAssetRate,    "\(name).weightedAssetRate")
        }
    }

    // MARK: - testNetWorthSummary

    func testNetWorthSummary() throws {
        let testCases = ["empty_month", "debt_heavy", "investment_portfolio",
                         "health_score_good", "health_score_poor", "net_worth_outlook_60"]

        for name in testCases {
            let fix = try fixture(named: name)
            let actual = FinanceEngine.netWorthSummary(fix.input.accounts)
            let exp    = fix.output.netWorthSummary

            assertEqual(actual.netWorth,    exp.netWorth,    "\(name).netWorth")
            assertEqual(actual.totalAssets, exp.totalAssets, "\(name).totalAssets")
            assertEqual(actual.totalDebt,   exp.totalDebt,   "\(name).totalDebt")
        }
    }

    // MARK: - testNetWorthOutlook

    func testNetWorthOutlook() throws {
        // The Swift engine uses `Date()` internally for labels; the JS engine uses a fixed
        // `startDate`.  We only compare numeric fields (not labels) for reliability.
        let testCases = ["debt_heavy", "investment_portfolio", "goals_basic", "net_worth_outlook_60"]

        for name in testCases {
            let fix = try fixture(named: name)
            guard let expPoints = fix.output.netWorthOutlook else {
                XCTFail("\(name): missing netWorthOutlook in fixture")
                continue
            }
            let horizonMonths = fix.input.horizonMonths ?? 60
            let proj = FinanceEngine.projection(for: fix.input.month)
            let actual = FinanceEngine.netWorthOutlook(
                accounts: fix.input.accounts,
                recurringMonthlySurplus: proj.recurringMonthlySurplus,
                horizonMonths: horizonMonths,
                assumedInvestmentReturn: DEFAULT_INVESTMENT_RETURN
            )

            XCTAssertEqual(actual.count, expPoints.count,
                           "\(name): netWorthOutlook point count mismatch")

            for (i, (a, e)) in zip(actual, expPoints).enumerated() {
                XCTAssertEqual(a.monthIndex, e.monthIndex, "\(name)[\(i)].monthIndex")
                assertEqual(a.netWorth,          e.netWorth,          "\(name)[\(i)].netWorth")
                assertEqual(a.assetBalance,      e.assetBalance,      "\(name)[\(i)].assetBalance")
                assertEqual(a.cashBalance,       e.cashBalance,       "\(name)[\(i)].cashBalance")
                assertEqual(a.savingsBalance,    e.savingsBalance,    "\(name)[\(i)].savingsBalance")
                assertEqual(a.investmentBalance, e.investmentBalance, "\(name)[\(i)].investmentBalance")
                assertEqual(a.debtBalance,       e.debtBalance,       "\(name)[\(i)].debtBalance")
                assertEqual(a.interestCharged,   e.interestCharged,   "\(name)[\(i)].interestCharged")
                assertEqual(a.growthEarned,      e.growthEarned,      "\(name)[\(i)].growthEarned")
            }
        }
    }

    // MARK: - testHealthScore

    func testHealthScore() throws {
        let testCases = ["empty_month", "basic_month", "debt_heavy", "investment_portfolio",
                         "health_score_good", "health_score_poor"]

        for name in testCases {
            let fix = try fixture(named: name)
            guard let exp = fix.output.healthScore else {
                XCTFail("\(name): missing healthScore in fixture")
                continue
            }
            let actual = FinanceEngine.healthScore(
                month: fix.input.month,
                accounts: fix.input.accounts,
                savingsTarget: fix.input.savingsTarget
            )

            assertEqual(actual.score,                exp.score,                "\(name).healthScore.score")
            XCTAssertEqual(actual.estimatedCreditScore, exp.estimatedCreditScore,
                           "\(name).healthScore.estimatedCreditScore")
            assertEqual(actual.cashFlowScore,        exp.cashFlowScore,        "\(name).healthScore.cashFlowScore")
            assertEqual(actual.debtLoadScore,        exp.debtLoadScore,        "\(name).healthScore.debtLoadScore")
            assertEqual(actual.utilizationScore,     exp.utilizationScore,     "\(name).healthScore.utilizationScore")
            assertEqual(actual.paymentPressureScore, exp.paymentPressureScore, "\(name).healthScore.paymentPressureScore")
            assertEqual(actual.savingsScore,         exp.savingsScore,         "\(name).healthScore.savingsScore")
            XCTAssertEqual(actual.summary,           exp.summary,              "\(name).healthScore.summary")
            XCTAssertEqual(actual.noData,            exp.noData,               "\(name).healthScore.noData")
        }
    }

    // MARK: - testGoalSequence

    func testGoalSequence() throws {
        let testCases = ["goals_basic", "goals_interest"]

        for name in testCases {
            let fix = try fixture(named: name)
            guard let exp = fix.output.goalSequence else {
                XCTFail("\(name): missing goalSequence in fixture")
                continue
            }
            let proj = FinanceEngine.projection(for: fix.input.month)
            let surplus = fix.input.monthlySurplus ?? proj.recurringMonthlySurplus
            let horizon = fix.input.horizonMonths ?? 36

            let actual = FinanceEngine.runGoalSequence(
                goals: fix.input.goals,
                monthlySurplus: surplus,
                horizonMonths: horizon
            )

            XCTAssertEqual(actual.horizonMonths,         exp.horizonMonths,         "\(name).goalSeq.horizonMonths")
            assertEqual(actual.avgUnallocatedSurplus,    exp.avgUnallocatedSurplus, "\(name).goalSeq.avgUnallocatedSurplus")
            XCTAssertEqual(actual.goals.count,           exp.goals.count,           "\(name).goalSeq.goals.count")
            XCTAssertEqual(actual.timeline.count,        exp.timeline.count,        "\(name).goalSeq.timeline.count")

            for (a, e) in zip(actual.goals, exp.goals) {
                XCTAssertEqual(a.goalId,         e.goalId,         "\(name).goal[\(e.goalId)].goalId")
                XCTAssertEqual(a.name,           e.name,           "\(name).goal[\(e.goalId)].name")
                assertEqual(a.target,            e.target,         "\(name).goal[\(e.goalId)].target")
                assertEqual(a.shortfall,         e.shortfall,      "\(name).goal[\(e.goalId)].shortfall")
                XCTAssertEqual(a.completionMonth,e.completionMonth,"\(name).goal[\(e.goalId)].completionMonth")
                XCTAssertEqual(a.status.rawValue,e.status.rawValue,"\(name).goal[\(e.goalId)].status")
            }

            // Spot-check the first timeline month.
            if let at = actual.timeline.first, let et = exp.timeline.first {
                XCTAssertEqual(at.month, et.month, "\(name).timeline[0].month")
                assertEqual(at.unallocated, et.unallocated, "\(name).timeline[0].unallocated")
                for goalId in et.perGoal.keys {
                    if let ap = at.perGoal[goalId], let ep = et.perGoal[goalId] {
                        assertEqual(ap.accumulated,  ep.accumulated,  "\(name).timeline[0][\(goalId)].accumulated")
                        assertEqual(ap.contribution, ep.contribution, "\(name).timeline[0][\(goalId)].contribution")
                        XCTAssertEqual(ap.complete,  ep.complete,     "\(name).timeline[0][\(goalId)].complete")
                    }
                }
            }
        }
    }

    // MARK: - testSeedMonth

    func testSeedMonth() throws {
        let fix = try fixture(named: "seed_from_previous")
        guard let exp = fix.output.seededMonth else {
            XCTFail("seed_from_previous: missing seededMonth in fixture")
            return
        }
        guard let prevMonth = fix.input.previousMonth else {
            XCTFail("seed_from_previous: missing previousMonth in fixture input")
            return
        }

        let actual = FinanceEngine.seedMonth(from: prevMonth)

        // Only the note should carry over; incomes and expenses start empty.
        XCTAssertEqual(actual.note, exp.note, "seededMonth.note")
        XCTAssertTrue(actual.incomes.isEmpty,  "seededMonth.incomes should be empty")
        XCTAssertTrue(actual.expenses.isEmpty, "seededMonth.expenses should be empty")
        XCTAssertEqual(actual.note, prevMonth.note, "seededMonth.note should equal previous month note")
    }

    // MARK: - testJsonRoundTrip

    /// Encodes a fixture LedgerState to JSON, decodes it back, and asserts structural equality.
    /// This validates that the Swift Codable implementation is wire-compatible with the web app's
    /// JSON representation (same key names, enum raw values, optional handling).
    func testJsonRoundTrip() throws {
        // Use the most data-rich fixture for the round-trip test.
        let fix = try fixture(named: "net_worth_outlook_60")
        let original = fix.input.state

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        let data = try encoder.encode(original)

        let decoder = JSONDecoder()
        let decoded = try decoder.decode(LedgerState.self, from: data)

        // Check top-level scalar fields.
        XCTAssertEqual(original.schemaVersion,         decoded.schemaVersion)
        XCTAssertEqual(original.currency,              decoded.currency)
        XCTAssertEqual(original.selectedMonth,         decoded.selectedMonth)
        XCTAssertEqual(original.savingsTarget,         decoded.savingsTarget)
        XCTAssertEqual(original.privacyMode,           decoded.privacyMode)
        XCTAssertEqual(original.goalsHorizonMonths,    decoded.goalsHorizonMonths)
        XCTAssertEqual(original.assumedInvestmentReturn, decoded.assumedInvestmentReturn)
        XCTAssertEqual(original.goalPlannerSurplus,    decoded.goalPlannerSurplus)
        XCTAssertEqual(original.ledgerGoalId,          decoded.ledgerGoalId)

        // Months
        XCTAssertEqual(Set(original.months.keys), Set(decoded.months.keys))
        for (key, origMonth) in original.months {
            guard let decMonth = decoded.months[key] else {
                XCTFail("Month '\(key)' missing after round-trip")
                continue
            }
            XCTAssertEqual(origMonth.note, decMonth.note)
            XCTAssertEqual(origMonth.incomes.count,  decMonth.incomes.count,  "month[\(key)].incomes.count")
            XCTAssertEqual(origMonth.expenses.count, decMonth.expenses.count, "month[\(key)].expenses.count")

            for (oi, di) in zip(origMonth.incomes, decMonth.incomes) {
                XCTAssertEqual(oi.id, di.id)
                XCTAssertEqual(oi.source, di.source)
                XCTAssertEqual(oi.amount, di.amount, accuracy: 1e-9)
                XCTAssertEqual(oi.color, di.color)
                XCTAssertEqual(oi.recurring, di.recurring)
                XCTAssertEqual(oi.date, di.date)
            }
            for (oe, de) in zip(origMonth.expenses, decMonth.expenses) {
                XCTAssertEqual(oe.id, de.id)
                XCTAssertEqual(oe.name, de.name)
                XCTAssertEqual(oe.category, de.category)
                XCTAssertEqual(oe.amount, de.amount, accuracy: 1e-9)
                XCTAssertEqual(oe.color, de.color)
                XCTAssertEqual(oe.recurring, de.recurring)
            }
        }

        // Accounts
        XCTAssertEqual(original.accounts.count, decoded.accounts.count)
        for (oa, da) in zip(original.accounts, decoded.accounts) {
            XCTAssertEqual(oa.id,                da.id)
            XCTAssertEqual(oa.name,              da.name)
            XCTAssertEqual(oa.accountClass,      da.accountClass)
            XCTAssertEqual(oa.type,              da.type)
            XCTAssertEqual(oa.balance,           da.balance,           accuracy: 1e-9)
            XCTAssertEqual(oa.rate,              da.rate,              accuracy: 1e-9)
            XCTAssertEqual(oa.promoRate,         da.promoRate,         accuracy: 1e-9)
            XCTAssertEqual(oa.promoMonths,       da.promoMonths)
            XCTAssertEqual(oa.monthlyContribution, da.monthlyContribution, accuracy: 1e-9)
            XCTAssertEqual(oa.creditLimit,       da.creditLimit,       accuracy: 1e-9)
            XCTAssertEqual(oa.minimumPayment,    da.minimumPayment,    accuracy: 1e-9)
            XCTAssertEqual(oa.dueDay,            da.dueDay)
            XCTAssertEqual(oa.includeInNetWorth, da.includeInNetWorth)
            XCTAssertEqual(oa.color,             da.color)
        }

        // Goals
        XCTAssertEqual(original.goals.count, decoded.goals.count)
        for (og, dg) in zip(original.goals, decoded.goals) {
            XCTAssertEqual(og.id,             dg.id)
            XCTAssertEqual(og.name,           dg.name)
            XCTAssertEqual(og.target,         dg.target,  accuracy: 1e-9)
            XCTAssertEqual(og.saved,          dg.saved,   accuracy: 1e-9)
            XCTAssertEqual(og.fundingMode,    dg.fundingMode)
            XCTAssertEqual(og.monthlyAmount,  dg.monthlyAmount,  accuracy: 1e-9)
            XCTAssertEqual(og.deadlineMonths, dg.deadlineMonths)
            XCTAssertEqual(og.interestRate,   dg.interestRate,   accuracy: 1e-9)
            XCTAssertEqual(og.priority,       dg.priority)
        }

        // CategoryRules
        XCTAssertEqual(original.categoryRules.count, decoded.categoryRules.count)
        for (or_, dr) in zip(original.categoryRules, decoded.categoryRules) {
            XCTAssertEqual(or_.id,       dr.id)
            XCTAssertEqual(or_.pattern,  dr.pattern)
            XCTAssertEqual(or_.category, dr.category)
            XCTAssertEqual(or_.kind,     dr.kind)
        }

        // ImportBatches
        XCTAssertEqual(original.importBatches.count, decoded.importBatches.count)
        for (ob, db) in zip(original.importBatches, decoded.importBatches) {
            XCTAssertEqual(ob.id,           db.id)
            XCTAssertEqual(ob.fileName,     db.fileName)
            XCTAssertEqual(ob.totalRows,    db.totalRows)
            XCTAssertEqual(ob.importedRows, db.importedRows)
            XCTAssertEqual(ob.skippedRows,  db.skippedRows)
            XCTAssertEqual(ob.transactionRefs.count, db.transactionRefs.count)
            for (or_, dr) in zip(ob.transactionRefs, db.transactionRefs) {
                XCTAssertEqual(or_.monthKey, dr.monthKey)
                XCTAssertEqual(or_.entryId,  dr.entryId)
                XCTAssertEqual(or_.kind,     dr.kind)
            }
        }
    }

    // MARK: - testMonthlyFlow

    func testMonthlyFlow() throws {
        // Monthly flow points depend on which year is in selectedMonth.
        // We compare the computed values for all months that have data in the fixture state.
        let testCases = ["basic_month", "debt_heavy", "investment_portfolio"]

        for name in testCases {
            let fix = try fixture(named: name)
            guard let expPoints = fix.output.monthlyFlow else { continue }

            let actual = FinanceEngine.monthlyFlowPoints(fix.input.state)

            XCTAssertEqual(actual.count, expPoints.count, "\(name).monthlyFlow.count")

            for (i, (a, e)) in zip(actual, expPoints).enumerated() {
                XCTAssertEqual(a.monthKey, e.monthKey, "\(name).flow[\(i)].monthKey")
                assertEqual(a.income,   e.income,   "\(name).flow[\(i)].income")
                assertEqual(a.expenses, e.expenses, "\(name).flow[\(i)].expenses")
                assertEqual(a.surplus,  e.surplus,  "\(name).flow[\(i)].surplus")
                XCTAssertEqual(a.hasData, e.hasData, "\(name).flow[\(i)].hasData")
            }
        }
    }
}

// MARK: - GoalSequenceResult Decodable

// The Swift GoalMonthPoint uses `perGoal: [String: GoalMonthPointPerGoal]` which matches
// the JS structure exactly — JSONDecoder handles dictionary-keyed objects natively.
// No custom Decodable implementation needed.

// MARK: - Notes on type compatibility

// `HealthScoreBreakdown` uses `estimatedCreditScore: Double` in Swift.
// The JS fixture emits it as an integer literal (e.g. 740).
// Swift's JSONDecoder coerces JSON integers to Double automatically, so no
// custom Decodable implementation is needed — the synthesised one works as-is.

// `GoalOutcome.extraMonthsNeeded` is `Double` in Types.swift to match the TS type,
// but the JS fixture may emit it as an integer (0). JSONDecoder coerces automatically.
