// Bank CSV import guides. One high-intent long-tail page per UK bank.
// `steps` are sourced from each bank's current export flow. Each entry may
// carry `published` (ISO date) so the sitemap/schema keep the original
// publish date; anything without it falls back to the site-wide default.

export const BANKS = [
  {
    slug: "barclays-csv",
    group: "High street banks",
    published: "2026-06-16",
    landing: "barclays-csv-budget-planner",
    name: "Barclays",
    where: "Barclays Online Banking on a computer (the app cannot export CSV)",
    steps: [
      "Log in to Barclays Online Banking on a computer.",
      "Choose the account you want and click <em>Show recent transactions</em>.",
      "Scroll down and click <em>View all transactions</em>.",
      "Pick a start and end date, then click <em>Search</em>.",
      "Scroll to the bottom, click <em>Export all</em>, then choose <em>CSV (Excel)</em>.",
      "Save the file and drop it into The Income Tracker.",
    ],
    note: "Barclays only offers CSV export on the desktop Online Banking site. The mobile app cannot do it.",
  },
  {
    slug: "hsbc-csv",
    group: "High street banks",
    published: "2026-06-16",
    name: "HSBC UK",
    where: "HSBC Online Banking on desktop, from the transactions list rather than the PDF statement",
    steps: [
      "Log in to HSBC UK Online Banking on a computer (a mobile browser works too, but not the app).",
      "Open the account you want to export.",
      "Go to the transactions or previous statements view for that account.",
      "Use the <em>Download</em> option and choose <em>CSV</em> (or Excel).",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "HSBC's official monthly statements are PDF only. CSV comes from the transactions list and usually covers recent activity, so export in chunks if you need more history.",
  },
  {
    slug: "monzo-csv",
    group: "App-based banks and fintechs",
    published: "2026-06-16",
    landing: "monzo-csv-expense-tracker",
    name: "Monzo",
    where: "the Monzo app (iOS or Android)",
    steps: [
      "Open the Monzo app and find your transaction feed.",
      "Tap <em>Manage</em> next to the account (or the three dots on a business card).",
      "Tap <em>Bank statements</em>.",
      "Choose the date range you want.",
      "Select <em>CSV</em> as the format and generate the statement.",
      "Share or save the file, then import it into The Income Tracker.",
    ],
    note: "Monzo also offers PDF and QIF. Pick CSV for the cleanest import.",
  },
  {
    slug: "starling-csv",
    group: "App-based banks and fintechs",
    published: "2026-06-16",
    landing: "starling-csv-budget-tracker",
    name: "Starling Bank",
    where: "the Starling app or web banking",
    steps: [
      "Open the Starling app and go to the account you want.",
      "Tap the account name, then <em>Account</em> or <em>Account information</em>.",
      "Tap <em>Statements</em> (or <em>Export statement</em>).",
      "Choose your date range and select <em>CSV</em> as the format.",
      "Save the file and drop it into The Income Tracker.",
    ],
    note: "Starling lets you export specific date ranges as CSV, which is handy for filling one month at a time.",
  },
  {
    slug: "lloyds-csv",
    group: "High street banks",
    published: "2026-06-16",
    name: "Lloyds Bank",
    where: "Lloyds Internet Banking on a computer (the app cannot export CSV)",
    steps: [
      "Log in to Lloyds Internet Banking on a computer.",
      "Open the account and find the <em>Statement options</em> box above the transactions.",
      "Click it and choose <em>Export transactions (CSV, QIF)</em>.",
      "Set your date range and choose <em>CSV</em>.",
      "The file downloads as <em>exportStatements-xx.csv</em>, ready to import into The Income Tracker.",
    ],
    note: "Lloyds caps each export at the last 12 months and 150 transactions. Hit the cap? Export again with a narrower date range and import each file.",
  },
  {
    slug: "natwest-csv",
    group: "High street banks",
    published: "2026-06-16",
    name: "NatWest",
    where: "NatWest Online Banking on desktop",
    steps: [
      "Log in to NatWest Online Banking on a computer.",
      "Select <em>Statements &amp; transactions</em> from the main menu.",
      "Choose <em>View transactions</em>, pick the account and set your date range.",
      "Click <em>View transactions</em>, then choose to export.",
      "From the format drop-down, select <em>Excel, Lotus, 123, Text (CSV file)</em>.",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "Always set the date range before exporting so you capture the full period you want.",
  },
  {
    slug: "santander-csv",
    group: "High street banks",
    published: "2026-06-16",
    name: "Santander UK",
    where: "Santander Online Banking on desktop",
    steps: [
      "Log in to Santander Online Banking on a computer.",
      "From <em>My accounts and transactions</em>, choose the account.",
      "Click <em>Download transactions</em> above the transactions table.",
      "In the <em>Download to</em> drop-down, choose <em>midata (CSV)</em>.",
      "Click <em>Download</em>, save the file, and import it into The Income Tracker.",
    ],
    note: "Santander's midata export covers up to 12 months and masks some sensitive details for security. That is normal and still imports fine.",
  },
  {
    slug: "revolut-csv",
    group: "App-based banks and fintechs",
    published: "2026-06-16",
    name: "Revolut",
    where: "the Revolut app or web app",
    steps: [
      "Open Revolut and go to <em>Accounts</em>.",
      "Tap <em>Statements</em> (under the account or in <em>Documents</em>).",
      "Choose your account or currency and date range.",
      "Select <em>Excel/CSV</em> as the format and generate it.",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "Revolut's CSV can include multi-currency columns. If a file looks messy, export one currency per file for the cleanest import.",
  },

  // ── Added September 2026. Steps verified against the provider's own help pages
  // where they exist, otherwise against accountancy import guides and consistent
  // user reports (see each entry's sources). Labels can drift; readers can flag it.
  {
    slug: "nationwide-csv",
    name: "Nationwide",
    group: "High street banks",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "the Nationwide Internet Bank on a computer (the Banking app only offers PDF statements)",
    formats: "CSV, OFX, midata (a CSV-style file) and PDF",
    steps: [
      "Log in to the Nationwide Internet Bank in a desktop browser, not the Banking app.",
      "Select the current account you want to export.",
      "Set the date range above the transaction list. The Internet Bank shows around 15 months.",
      "Click <em>Download transactions</em> at the top right of the transactions list.",
      "Choose <em>Download CSV file</em>. OFX and midata are offered too.",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "Download transactions appears on current accounts and credit cards. Some savings accounts only offer PDF statements, which you can still paste in. Older months live under Documents, then Statements, as PDFs going back 36 months.",
    faqs: [
      { q: "Can I export a CSV from the Nationwide app?", a: "No. The Banking app only produces PDF statements. Use the Internet Bank in a browser for CSV, OFX or midata files. On an iPhone or iPad the browser can show the option but may not download it, so a computer is the reliable route." },
    ],
    sources: [
      { t: "Nationwide: about midata downloads", href: "https://www.nationwide.co.uk/help/online-banking-help/about-midata" },
      { t: "Dead Simple Accounting: downloading a Nationwide statement (January 2026)", href: "https://www.deadsimpleaccounting.co.uk/how-to-download-a-bank-statement-from-nationwide-for-accounting/" },
      { t: "MoneySavingExpert forum: Nationwide download transactions", href: "https://forums.moneysavingexpert.com/discussion/6408564/cannot-download-transactions-for-nationwide-esavings-account" },
    ],
  },
  {
    slug: "halifax-csv",
    name: "Halifax",
    group: "High street banks",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "Halifax Online Banking in a web browser (the app only offers PDF statements)",
    formats: "CSV, QIF, PDF and a 12-month midata export",
    steps: [
      "Log in to Halifax Online Banking in a browser and open the account.",
      "Click <em>Search</em>, next to <em>All transactions</em>.",
      "Click <em>Edit date range</em> and enter your from and to dates. Each search covers up to 12 months, going back seven years. Click <em>Continue</em>.",
      "Leave the description and amount boxes blank, keep <em>All transaction types</em>, and run the search.",
      "Scroll to the bottom of the results and choose <em>Export .CSV</em>. <em>Export .QIF</em> sits next to it.",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "Each export covers at most 12 months, so a longer history means a few files. Overlaps are fine: the tracker drops duplicates. Credit card statements are not downloadable in Online Banking, only in the app as PDFs.",
    faqs: [
      { q: "Why can't I find the CSV export in the Halifax app?", a: "Because it is not there. The app's three-dot menu offers Download or print statement, which gives a PDF. CSV and QIF exports live on the website under Search transactions." },
    ],
    sources: [
      { t: "Halifax: download or print statements", href: "https://www.halifax.co.uk/helpcentre/everyday-banking/statements/download-statements.html" },
      { t: "Max Tax Back: exporting a Halifax statement (screenshots)", href: "https://maxtaxback.co.uk/business-banking-support-hub/export-a-halifax-statement/" },
      { t: "MoneySavingExpert forum: CSV transaction downloads by card", href: "https://forums.moneysavingexpert.com/discussion/6477826/which-credit-cards-offer-csv-transaction-downloads-and-for-how-many-months-years" },
    ],
  },
  {
    slug: "bank-of-scotland-csv",
    name: "Bank of Scotland",
    group: "High street banks",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "Bank of Scotland Internet Banking in a web browser (the app only offers PDF statements)",
    formats: "CSV, QIF and PDF",
    steps: [
      "Log in to Internet Banking in a browser and open the account.",
      "Open <em>Search transactions</em> and use <em>Edit date range</em> to set from and to dates, up to 12 months at a time.",
      "Leave the description and amount boxes blank and run the search.",
      "At the bottom of the results choose <em>Export .CSV</em> or <em>Export .QIF</em>.",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "Bank of Scotland shares its online platform with Halifax and Lloyds, so the screens match those guides. Business Internet Banking has the export under Statement options, then Export transactions (CSV, QIF), with a cap of 1,000 lines per file.",
    faqs: [
      { q: "Does the Bank of Scotland app export CSV?", a: "No. The app offers PDF statements only. Use Internet Banking in a browser for CSV or QIF." },
    ],
    sources: [
      { t: "Bank of Scotland: download or order a statement", href: "https://www.bankofscotland.co.uk/helpcentre/everyday-banking/statements/download-or-order-statement.html" },
      { t: "Bank of Scotland Business: view your bank statement", href: "https://business.bankofscotland.co.uk/help/account-management/view-your-bank-statement.html" },
      { t: "MoneySavingExpert forum: credit card export format", href: "https://forums.moneysavingexpert.com/discussion/6608740/credit-card-export-format" },
    ],
  },
  {
    slug: "tsb-csv",
    name: "TSB",
    group: "High street banks",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "TSB Internet Banking on a computer (the app only offers PDF statements in your Inbox)",
    formats: "CSV, QIF and PDF",
    steps: [
      "Log in to TSB Internet Banking on a computer.",
      "Click the account name to open its transactions.",
      "Scroll to the bottom of the list and click <em>Export</em>.",
      "Choose <em>Date Range</em> and enter start and end dates. Each file covers up to 90 days or 150 transactions.",
      "Pick <em>CSV</em> and click <em>Export</em>. The file is named exportStatements-xx.csv.",
      "Repeat with new dates for a longer period, then import each file into The Income Tracker.",
    ],
    note: "The 90-day, 150-transaction cap means a full year takes four or five files. Overlapping ranges are safe because the tracker drops duplicates. TSB's CSV dates carry a time stamp, which the importer strips.",
    faqs: [
      { q: "Can I export more than 90 days from TSB at once?", a: "Not in one file. Run the export several times with consecutive date ranges. Users report being able to go back at least five years this way." },
    ],
    sources: [
      { t: "TSB: view and download statements", href: "https://www.tsb.co.uk/help-and-support/how-to/view-and-download-statements.html" },
      { t: "EN Accounting: downloading a CSV from TSB", href: "https://enaccounting.com/download-csv-lloyds-tsb/" },
      { t: "MoneySavingExpert forum: TSB QIF download", href: "https://forums.moneysavingexpert.com/discussion/6318176/tsb-qif-file-download" },
    ],
  },
  {
    slug: "chase-uk-csv",
    name: "Chase UK",
    group: "App-based banks and fintechs",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "the Chase app (Chase has no web banking)",
    formats: "CSV and PDF",
    steps: [
      "Open the Chase app and tap your profile icon.",
      "Tap <em>Statements</em>.",
      "Pick a monthly statement, or create a custom statement with a date range of up to 90 days.",
      "Choose <em>CSV</em> as the format. PDF is the other option.",
      "Save or share the file to your computer or cloud drive, then import it into The Income Tracker.",
    ],
    note: "Custom statements are capped at 90 days each. Monthly statements appear on the 2nd of the following month (the 3rd for the credit card) and stay available for six years, even after you close the account.",
    faqs: [
      { q: "Is Chase UK PDF only?", a: "Not any more. Chase's own support page says statements can be exported as PDF or CSV, and that a custom statement can cover up to 90 days. Older third-party guides that say PDF only are out of date." },
    ],
    sources: [
      { t: "Chase UK: statements", href: "https://www.chase.co.uk/gb/en/support/statements/" },
      { t: "MoneySavingExpert forum: Chase statements thread (2023, PDF only at the time)", href: "https://forums.moneysavingexpert.com/discussion/6476698/chase-account-statements-pdf-only" },
    ],
  },
  {
    slug: "first-direct-csv",
    name: "first direct",
    group: "High street banks",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "first direct Online Banking in a desktop browser (the app only offers PDF statements)",
    formats: "CSV, QIF (Quicken and Microsoft Money flavours), JSON and PDF",
    steps: [
      "Log on to Online Banking in a desktop browser. The download option does not show in the app and is often hidden on phones.",
      "Select the account to open its transactions page.",
      "Use the download option on the transactions page and set a date range of up to one year.",
      "Choose <em>CSV</em>. QIF and JSON are also offered.",
      "Download, then repeat for each earlier year you need. Current accounts go back up to six years.",
      "Import each file into The Income Tracker.",
    ],
    note: "first direct's own help pages only describe PDF statements, so the label on the download option may differ from what you expect. Look on the transactions page rather than under Statements. Credit card exports cover a shorter period, around six months.",
    faqs: [
      { q: "Does first direct still offer QIF?", a: "Users report it disappeared in one redesign and came back later. CSV has been consistently available on the desktop site, which is the format the tracker prefers anyway." },
    ],
    sources: [
      { t: "first direct: statements and balances", href: "https://www.firstdirect.com/help/bank-accounts/statements-and-balances/" },
      { t: "MoneySavingExpert forum: accounts that export a year in one go", href: "https://forums.moneysavingexpert.com/discussion/6658217/current-account-with-ability-to-export-annual-transactions-in-1-go" },
      { t: "PistonHeads: first direct transaction downloads", href: "https://www.pistonheads.com/gassing/topic.asp?h=0&f=206&t=2040689" },
    ],
  },
  {
    slug: "amex-csv",
    name: "American Express",
    group: "Credit cards and business accounts",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "your American Express online account in a desktop browser (the app shows PDF statements only)",
    formats: "CSV, Excel and PDF (QIF and OFX have been withdrawn)",
    steps: [
      "Log in to your American Express online account in a desktop browser.",
      "Open <em>Statements &amp; Activity</em>.",
      "Pick a statement period, or choose <em>Custom Date Range</em>, enter your dates and search.",
      "Click the download icon above the transaction list.",
      "Choose <em>CSV</em>. Tick the option to include all additional transaction details if you want the extra columns.",
      "Download the file and import it into The Income Tracker.",
    ],
    note: "Card statements list spending as positive numbers. The tracker spots this and flips the signs so purchases land as expenses, with a one-click undo if it guesses wrong. Roughly two years of transactions are downloadable; older periods are PDF only.",
    faqs: [
      { q: "Why do my Amex purchases import as income?", a: "Credit card exports show purchases as positive amounts. The Income Tracker detects that pattern and flips the signs automatically. If a file slips through, use the flip button in the import review." },
      { q: "Can I get a QIF or OFX file from Amex UK?", a: "Not any more. Amex removed the Quicken and Money formats; CSV, Excel and PDF remain. CSV imports directly." },
    ],
    sources: [
      { t: "American Express UK: receiving card statements", href: "https://www.americanexpress.com/en-gb/customer-service/payments-and-billings/faq.receive-card-statements.html" },
      { t: "Dead Simple Accounting: downloading an American Express statement", href: "https://www.deadsimpleaccounting.co.uk/how-to-download-a-bank-statement-from-american-express/" },
      { t: "Finaloop: uploading American Express CSV statements", href: "https://help.finaloop.com/en/articles/9582937-american-express-how-to-upload-your-csv-bank-statements" },
    ],
  },
  {
    slug: "virgin-money-csv",
    name: "Virgin Money",
    group: "High street banks",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "Virgin Money Internet Banking in a desktop browser (the app offers PDF statements only)",
    formats: "CSV (basic or detailed) and PDF",
    steps: [
      "Sign in to Virgin Money Internet Banking in a desktop browser, not the app.",
      "Click the account you want to export.",
      "Find the download or print option above the transaction list.",
      "Set the date range.",
      "Choose <em>CSV</em>, picking the detailed version if offered, and click <em>Export transactions</em>.",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "Virgin Money says the export is not available on every account type. If yours only shows PDF statements, copy the transactions out of the PDF and paste them in instead.",
    faqs: [
      { q: "Can I export a CSV from the Virgin Money app?", a: "No. The app produces PDF statements. CSV export is on Internet Banking in a browser, and only for some account types." },
    ],
    sources: [
      { t: "Virgin Money: downloading business transactions", href: "https://uk.virginmoney.com/service/guides/business-banking/downloading-business-transactions/" },
      { t: "Virgin Money: view and download a statement", href: "https://support.virginmoney.com/subtopic/pagecontent/article/KA-01602" },
      { t: "Dead Simple Accounting: Virgin Money statements", href: "https://www.deadsimpleaccounting.co.uk/how-to-download-bank-statements-from-virgin-money-for-accounting/" },
    ],
  },
  {
    slug: "co-operative-bank-csv",
    name: "Co-operative Bank",
    group: "High street banks",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "Co-operative Bank online banking in a desktop browser",
    formats: "CSV (personal); CSV, PDF, TXT and XLS (business)",
    steps: [
      "Log in to online banking in a desktop browser.",
      "Open the account and go to its transactions.",
      "Run a transaction search for the date range you want. The download option only appears after a search.",
      "Click <em>Download</em> (labelled <em>Download CSV</em> on some accounts) and choose CSV.",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "The export is easy to miss because it only shows once you have searched. Personal exports include Date, Description, Type, Money In, Money Out and Balance columns, which the tracker reads directly. Business online banking keeps 25 months of transactions.",
    faqs: [
      { q: "Can I export a whole year from the Co-operative Bank in one go?", a: "Users report yes: run one search for the full date range and download a single CSV." },
    ],
    sources: [
      { t: "The Co-operative Bank Business: can I export transaction information?", href: "https://www.co-operativebank.co.uk/business/faqs/ways-to-bank/online-banking/statements-and-transactions/can-I-export-transaction-information/prod-11451" },
      { t: "ExpensePlus: downloading a Co-op statement as CSV", href: "https://support.expenseplus.co.uk/article/522-how-do-i-download-my-coop-statement-as-csv" },
      { t: "MoneySavingExpert forum: exporting annual transactions", href: "https://forums.moneysavingexpert.com/discussion/6658217/current-account-with-ability-to-export-annual-transactions-in-1-go" },
    ],
  },
  {
    slug: "metro-bank-csv",
    name: "Metro Bank",
    group: "High street banks",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "Metro Bank Internet Banking in a desktop browser (the app offers PDF statements only)",
    formats: "CSV and PDF",
    steps: [
      "Log in to Internet Banking in a desktop browser and allow pop-ups for the site. The export opens in a pop-up and fails silently if it is blocked.",
      "Click the account to open its <em>Transaction Summary</em>. By default it shows the last 32 days.",
      "For a longer period click <em>Advanced Search</em>, enter your dates and click <em>Search</em>.",
      "Click <em>Export</em> to download a CSV. <em>Download</em> gives a PDF instead.",
      "Save the file and import it into The Income Tracker.",
    ],
    note: "Advanced Search reaches back to when the account opened. Metro's CSV writes dates like 12-Sep-26 and puts commas in large amounts; the importer handles both.",
    faqs: [
      { q: "Why does nothing happen when I click Export in Metro Bank?", a: "Almost always a pop-up blocker. Allow pop-ups for the Metro Bank site and try again." },
    ],
    sources: [
      { t: "Metro Bank: exporting transaction data (user guide)", href: "https://www.metrobankonline.co.uk/globalassets/documents/customer_documents/business-and-commercial/user-guide-exporting-transaction-data.pdf" },
      { t: "Clear Books: Metro Bank statement import guide", href: "https://support.clearbooks.co.uk/support/solutions/articles/33000274569-metro-bank-statement-import-guide" },
      { t: "Max Tax Back: export a Metro statement", href: "https://maxtaxback.co.uk/business-banking-support-hub/export-a-metro-statement/" },
    ],
  },
  {
    slug: "wise-csv",
    name: "Wise",
    group: "App-based banks and fintechs",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "the Wise app or wise.com",
    formats: "CSV, Excel, PDF, QIF, MT940 and CAMT.053",
    steps: [
      "Log in at wise.com or open the app.",
      "Open the balance you want, tap the three dots, then <em>Statements and reports</em>.",
      "Choose <em>Create a statement</em> and pick the balance. On the web you can select several at once.",
      "Set the period, up to 365 days per statement.",
      "Choose <em>CSV</em> as the format.",
      "Confirm with your password, download, and import the file into The Income Tracker.",
    ],
    note: "One statement per currency balance, 365 days each. Payments made straight from an external card do not appear in statements, only on the Transactions page, so check that page if something is missing.",
    faqs: [
      { q: "Can I export all my Wise currencies in one file?", a: "On the web you can select several balances when creating a statement. Multi-currency files import, but one currency per file gives the cleanest result." },
    ],
    sources: [
      { t: "Wise: how do I download a statement?", href: "https://www.wise.com/help/articles/2736049/how-do-i-download-a-statement" },
      { t: "StatementBridge: downloading a Wise bank statement", href: "https://www.statementbridge.nl/en/blog/download-bank-statement-wise" },
    ],
  },
  {
    slug: "tide-csv",
    name: "Tide",
    group: "Credit cards and business accounts",
    published: "2026-09-08",
    checked: "2026-09-08",
    where: "the Tide app or web app",
    formats: "CSV (standard and accounting-package layouts) and PDF statements",
    steps: [
      "In the Tide app, tap <em>Pay</em>, then <em>Find a transaction</em>, and filter by date range.",
      "Tap <em>View more</em> under the list, then the export icon at the top right.",
      "Choose the <em>Standard</em> CSV and tap <em>Export</em>, then save or share the file.",
      "On the web instead: go to <em>Accounts</em>, choose the account, click the funnel icon, set your filters, click <em>Apply Filter</em>, then <em>Export</em>.",
      "Import the file into The Income Tracker.",
    ],
    note: "The Standard CSV excludes pending transactions, so export once the month has settled. Official PDF statements arrive on the 4th of the following month, and custom-range statements can cover up to six months.",
    faqs: [
      { q: "Can I track my Tide business account alongside personal spending?", a: "Yes. Import the Tide CSV and give the business rows their own categories, or keep a separate ledger for the business. The self-employed template on this site uses Self Assessment expense headings." },
    ],
    sources: [
      { t: "Tide: download account statements and transactions", href: "https://www.tide.co/help-centre/download-tide-account-statements-and-transactions/" },
      { t: "Husa Accountants: Tide bank instructions", href: "https://husaaccountants.com/tide-bank-instructions/" },
    ],
  },
];
